import { UserContext } from 'context/userContext';
import Head from 'next/head';
import React, { useContext } from 'react';

export default function Home({ sheetdata }) {
  const [user, setUser] = useContext(UserContext);
  console.log(user);

  return (
    <div>
      <Head>
        <title>Budget Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{sheetdata}</h1>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const req = await fetch('http://localhost:3000/api/sheet');
  const res = await req.json();

  return {
    props: {
      sheetdata: res.data,
    },
  };
}
